### ISSUE TITLE
Airlines manager Bot

### ISSUE THREAD

**Issue by Stiker839** [janxbittner/Py.Bootcamp#1]
Any chance you could either send me the code for the AM4 bot or reupload it :)

**Comment by janxbittner** [comment]
Hi,
Feel free to download the code.
I didn't change this code so some functionality can don't work because the
airline website can change the layout of a page or something.
I learn how to automatize stuff from this guy:
https://www.youtube.com/watch?v=lvFAuUcowT4&t=2s&ab_channel=CodeDripbyAaronJack
Maybe for you that will be helpful too.

Best regards,
Jan

pon., 28 gru 2020 o 16:25 Striker <notifications@github.com> napisał(a):

**Comment by Stiker839** [comment]
Hi thanks for your response, I think you may have misunderstood me :)

Your original link does not work anymore so I cant find the code to download could you post a link to it please :)

**Comment by janxbittner** [comment]
Here you can find the code:
https://github.com/janxbittner/Automatization_with_Selenium/tree/main/Airline_Menager_4_Bot

pon., 28 gru 2020 o 21:55 Striker <notifications@github.com> napisał(a):

**Comment by Stiker839** [comment]
Hi thanks for your help I believe I have fixed it based on the video you shared :)
